spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.2
    port: 6379
    timeout: 3000ms
    database: 0
    jedis:
      pool:
        max-idle: 50
        min-idle: 5
        max-active: 200
        max-wait: 20ms
    lettuce:
      pool:
        max-active: 200
        max-wait: 20ms
        max-idle: 50
        min-idle: 5

redis:
  cache:
    expiration: 3600

---
spring:
  profiles:
    active: prd
  redis:
    host: 123.207.165.206
    port: 6379
    timeout: 3000ms
    database: 0
    jedis:
      pool:
        max-idle: 50
        min-idle: 5
        max-active: 200
        max-wait: 20ms
    lettuce:
      pool:
        max-active: 200
        max-wait: 20ms
        max-idle: 50
        min-idle: 5

redis:
  cache:
    expiration: 3600