server:
  port: 4060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Summer900108@
    url: jdbc:mysql://123.207.165.206:3306/vole?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 123.207.165.206:2181
      namespace: vole-job
